import type { Metadata } from "next";
import path from "node:path";
import fs from "node:fs/promises";

import { getGlobalKpisData } from "@/lib/market-data";

export const metadata: Metadata = {
  title: "Methodology & Data Governance | Global Catastrophe Bond Intelligence Platform"
};

interface AuditSummary {
  generated_at?: string;
  source_root?: string;
  source_files?: Record<string, string>;
  row_counts?: {
    raw_rows?: number;
    duplicate_rows_removed?: number;
    cleaned_rows?: number;
  };
  deduplication?: {
    primary_key?: string;
    duplicates_by_deal_id?: number;
    duplicates_by_fallback_key?: number;
    missing_deal_id_rows?: number;
  };
  amount_methodology?: {
    required_column?: string;
    rule?: string;
    total_market_volume_musd?: number;
    total_market_volume_usd?: number;
  };
}

export default async function MethodologyPage() {
  const [globalKpis, audit] = await Promise.all([getGlobalKpisData(), readAuditSummary()]);

  return (
    <div className="space-y-6">
      <section className="glass-panel p-6 md:p-8">
        <p className="text-xs uppercase tracking-[0.18em] text-cyan-200/90">Research & Tools</p>
        <h1 className="mt-2 text-3xl font-semibold text-white md:text-4xl">Methodology & Data Governance</h1>
        <p className="mt-3 max-w-4xl text-sm text-slate-300">
          Source hierarchy, classification logic, KPI governance, deduplication standards, and assumptions used across
          the Global Catastrophe Bond Intelligence Platform.
        </p>
      </section>

      <section className="grid gap-5 xl:grid-cols-2">
        <article className="glass-panel p-5">
          <h2 className="text-xl font-semibold text-white">Source Hierarchy</h2>
          <div className="mt-4 space-y-2 text-sm text-slate-300">
            <p>1. SQL-ready master package (`deals_master_sql_ready.csv`) as the transaction-level source of truth.</p>
            <p>2. Country Excel intelligence folders converted to normalized country JSON bundles.</p>
            <p>3. Derived chart and KPI JSON datasets generated by deterministic scripts.</p>
          </div>
        </article>
        <article className="glass-panel p-5">
          <h2 className="text-xl font-semibold text-white">Classification Rules</h2>
          <div className="mt-4 space-y-2 text-sm text-slate-300">
            <p>
              Sovereign classification uses `government_program_flag` as the primary rule and normalizes market segment
              labels into sovereign and non-sovereign analytics tracks.
            </p>
            <p>
              Peril and trigger dimensions are normalized into consistent platform categories to support cross-country and
              cross-period comparability.
            </p>
          </div>
        </article>
      </section>

      <section className="glass-panel p-5">
        <h2 className="text-xl font-semibold text-white">KPI Logic</h2>
        <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          <KpiCard label="Total Deals" value={globalKpis.total_deals.toLocaleString("en-US")} />
          <KpiCard
            label="Total Market Volume"
            value={`$${(globalKpis.total_market_volume_usd / 1_000_000_000).toFixed(3)}B`}
          />
          <KpiCard label="Sovereign Deals" value={globalKpis.sovereign_deal_count.toLocaleString("en-US")} />
          <KpiCard label="Non-Sovereign Deals" value={globalKpis.non_sovereign_deal_count.toLocaleString("en-US")} />
          <KpiCard label="Countries Covered" value={globalKpis.countries_covered.toLocaleString("en-US")} />
          <KpiCard label="Latest Market Year" value={String(globalKpis.latest_market_year ?? "N/A")} />
        </div>
      </section>

      <section className="grid gap-5 xl:grid-cols-2">
        <article className="glass-panel p-5">
          <h2 className="text-xl font-semibold text-white">Data Audit Snapshot</h2>
          <dl className="mt-4 space-y-2 text-sm">
            <Row label="Generated At" value={audit.generated_at ?? "N/A"} />
            <Row label="Source Root" value={audit.source_root ?? "N/A"} />
            <Row label="Raw Rows" value={String(audit.row_counts?.raw_rows ?? "N/A")} />
            <Row label="Duplicate Rows Removed" value={String(audit.row_counts?.duplicate_rows_removed ?? "N/A")} />
            <Row label="Cleaned Rows" value={String(audit.row_counts?.cleaned_rows ?? "N/A")} />
            <Row label="Primary Dedup Key" value={audit.deduplication?.primary_key ?? "N/A"} />
            <Row label="Missing Deal IDs" value={String(audit.deduplication?.missing_deal_id_rows ?? "N/A")} />
          </dl>
        </article>
        <article className="glass-panel p-5">
          <h2 className="text-xl font-semibold text-white">Assumptions vs Official Data</h2>
          <div className="mt-4 space-y-2 text-sm text-slate-300">
            <p>Official data: raw transaction records, event dates, issuance values, sponsor, peril, and trigger fields.</p>
            <p>Derived data: KPIs, heatmaps, distributions, and spread-vs-EL analytics from cleaned master records.</p>
            <p>
              Illustrative assumptions: policy simulation modules (for example Israel Lab trigger ladders and timing
              scenarios).
            </p>
            <p>
              Missing values are handled conservatively: records with incomplete pricing are excluded from pricing-only
              metrics while remaining in deal-count and issuance totals.
            </p>
          </div>
        </article>
      </section>
    </div>
  );
}

async function readAuditSummary(): Promise<AuditSummary> {
  try {
    const filePath = path.join(process.cwd(), "data", "master", "data_audit_summary.json");
    const text = await fs.readFile(filePath, "utf8");
    return JSON.parse(text) as AuditSummary;
  } catch {
    return {};
  }
}

function KpiCard({ label, value }: { label: string; value: string }) {
  return (
    <article className="rounded-xl border border-white/10 bg-slate-900/55 p-4">
      <p className="text-[11px] uppercase tracking-[0.14em] text-slate-300">{label}</p>
      <p className="mt-2 text-xl font-semibold text-cyan-100">{value}</p>
    </article>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <dt className="text-slate-400">{label}</dt>
      <dd className="text-slate-200">{value}</dd>
    </div>
  );
}
